export const registerColumn = [
  {
    id: 1,
    title: 'First Name',
    model: 'firstName',
    required: true,
    placeholder: 'Enter First Name',
    type: 'text',
  },
  {
    id: 2,
    title: 'Last name',
    model: 'lastName',
    placeholder: 'Enter Last Name',
    required: true,
    type: 'text',
  },
  {
    id: 3,
    title: 'Email',
    model: 'email',
    placeholder: 'Enter email',
    required: true,
    type: 'text',
  },
  {
    id: 4,
    title: 'Password',
    model: 'password',
    placeholder: 'Password',
    required: true,
    type: 'password',
  },
  {
    id: 5,
    title: 'Repeat password',
    model: 'repeatPassword',
    placeholder: 'Repeat Password',
    required: true,
    type: 'password',
  },
];
