name: lint/test check

on:
  workflow_dispatch:
  pull_request:
    branches: [dev]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js lts
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: Install deps
      run: npm ci
    - name: Check lint
      run: npm run lint
    - name: Check tests
      run: npm run test
